pipeline:
  build:
    image: node:10-alpine
    commands:
      - npm install
      - npm run lint
      - npm test

  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: deployment
      environment: production

  publish_npm:
    image: plugins/npm
    when:
      event: deployment
      environment: production

  # TODO publish npm

  slack_blame:
    image: plugins/slack-blame
    secrets: [ slack_token ]
    channel: paxdb-build-bot
    success_template: |
      paxdb/orthology-lib build is green :) Thanks {{user.name}}
    failure_template: |
      paxdb/orthology-lib build is broken :( Blame {{user.name}}
    when:
      status:  [ failure, success ]


branches: master
