pipeline:
  build:
    image: node:8-alpine
    commands:
      - npm install
      - npm run lint
      - npm test

  npm_auth:
    image: robertstettner/drone-npm-auth
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      event: deployment
      environment: production

  publish_npm:
    image: plugins/npm
    when:
      event: deployment
      environment: production

  slack_blame:
    image: plugins/slack-blame
    secrets: [ slack_token ]
    channel: paxdb-build-bot
    success_template: |
      The build is green :) Thanks @{{slack.name}}
    failure_template: |
      The build is broken! Blame {{slack.name}}


branches: master
