---
# fly -t dev login $IP
# fly -t dev set-pipeline -p paxdb-api-orthology-storage -c ci/pipeline.yml --var "registry-password=secret"
# fly -t dev unpause-pipeline  -p paxdb-api-orthology-storage
# fly -t dev trigger-job --job paxdb-api-orthology-storage/test
resources:
- name: code
  type: git
  source:
    uri: https://github.com/meringlab/paxdb-api-orthology-storage.git

jobs:
- name: test
  public: true
#  serial: true
  plan:
  - get: code
    trigger: true

  - task: compile-test-code
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker-registry.meringlab.org:5443/meringlab/node6
          username: admin
          password: {{registry-password}}
      #    repository: meringlab/node6
          tag: latest
      inputs:
        - name: code
      run:
        path: ./ci/test.sh
        dir: ./code/
