---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/meringlab/paxdb-api-orthology-storage.git

jobs:
- name: test
  public: true
#  serial: true
  plan:
  - get: code
    trigger: true
  - task: compile-test-code
    file: code/ci/task_run_tests.yml
