---

# fly -t dev login $IP
# fly -t dev set-pipeline -p paxdb-orthology -c ci/pipeline.yml --var "registry-password=secret"
# fly -t dev unpause-pipeline  -p paxdb-orthology
# fly -t dev trigger-job --job paxdb-orthology/build

resources:
- name: code
  type: git
  source:
    uri: https://github.com/meringlab/paxdb-orthology.git

- name: orthology-storage-index-image
  type: docker-image
  source:
    repository: docker-registry.meringlab.org:5443/paxdb/orthology-storage-index
    username: admin
    email: paxdb.team@gmail.com
    password: {{registry-password}}

- name: ubuntu-xenial
  type: docker-image
  source:
    repository: ubuntu
    tag: "xenial"

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - get: ubuntu-xenial
    trigger: true
    params: {save: true}
  - task: compile-test-code
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: docker-registry.meringlab.org:5443/meringlab/node6
          username: admin
          password: {{registry-password}}
      #    repository: meringlab/node6
          tag: latest
      inputs:
        - name: code
      run:
        path: ./ci/test.sh
        dir: ./code/
  # todo integration test, need to make an image with both java and node
  - put: orthology-storage-index-image
    params:
    # see https://github.com/concourse/docker-image-resource#parameters-1 for details
      build: code/
      dockerfile: code/Dockerfile.index
      load_base: ubuntu-xenial
#      tag: latest
  - put: orthology-api
    params:
    # see https://github.com/concourse/docker-image-resource#parameters-1 for details
      build: code/
      dockerfile: code/Dockerfile.front
      load_base: ubuntu-xenial
#      tag: latest
