---

# fly -t dev login $IP
# fly -t dev set-pipeline -p paxdb-orthology -c ci/pipeline.yml --var "registry-password=secret"
# fly -t dev unpause-pipeline  -p paxdb-orthology
# fly -t dev trigger-job --job paxdb-orthology/build

resources:
- name: code
  type: git
  source:
    uri: https://github.com/meringlab/paxdb-orthology.git

- name: meringlab-node6
  type: docker-image
  source:
    repository: docker-registry.meringlab.org:5443/meringlab/node6
    username: admin
    password: {{registry-password}} # should come as a param
    tag: latest
    #      repository: meringlab/node6

- name: orthology-storage-index-image
  type: docker-image
  source:
    repository: docker-registry.meringlab.org:5443/paxdb/orthology-storage-index
    username: admin
    email: paxdb.team@gmail.com
    password: {{registry-password}}

- name: orthology-api-image
  type: docker-image
  source:
    repository: docker-registry.meringlab.org:5443/paxdb/orthology-api
    username: admin
    email: paxdb.team@gmail.com
    password: {{registry-password}}

- name: ubuntu-xenial
  type: docker-image
  source:
    repository: ubuntu
    tag: "xenial"

jobs:
- name: storage
  public: true
  serial: true
  plan:
#TODO
#- aggregate:
  - get: code
    trigger: false
  - get: meringlab-node6
    params: {save: true}
  - get: ubuntu-xenial
    params: {save: true}
  - task: compile-test-code
    file: code/ci/build-task.yml
    image: meringlab-node6

  # todo integration test, need to make an image with both java and node

  - put: orthology-storage-index-image
    params:
      build: code/
      dockerfile: code/Dockerfile.index
      load_base: ubuntu-xenial
      tag: 4.0.4

- name: api
  public: true
  serial: false
  plan:
#TODO
#- aggregate:
  - get: code
    trigger: true
  - get: ubuntu-xenial
    params: {save: true}
  - get: meringlab-node6
    params: {save: true}
  - task: compile-test-code
    file: code/ci/build-task.yml
    image: meringlab-node6
  # todo integration test, need a storage container
  - put: orthology-api-image
    params:
    # see https://github.com/concourse/docker-image-resource#parameters-1 for details
      build: code/
      dockerfile: code/Dockerfile.front
      load_base: ubuntu-xenial
      tag: 4.0.4
